# [Prod 환경 변수 설정]

# 1. 서비스 주소 (Kubernetes DNS)
USER_SERVICE: http://user-service.default.svc.cluster.local
SOCIAL_SERVICE: http://social-service.default.svc.cluster.local
DIARY_SERVICE: http://diary-service.default.svc.cluster.local
PETMATE_SERVICE: http://petmate-service.default.svc.cluster.local
SHOPPING_SERVICE: http://shopping-service.default.svc.cluster.local

# 2. CORS 허용 도메인 (CloudFront)
CORS_ALLOWED_ORIGIN: https://d3uvkb1qxxcp2y.cloudfront.net

# 3. JWT 설정 (K8s Secret에서 주입)
TOKEN_SECRET: ${ENV_TOKEN_SECRET}
TOKEN_EXPIRATION_TIME: ${ENV_TOKEN_EXPIRATION_TIME}

# 4. Actuator (Health Check)
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
